column_map:
  item_code: ["kód", "kod", "code", "položka", "pol.", "pol", "item id"]
  item_desc: ["popis", "description", "item description", "název položky", "name"]
  unit: ["jednotka", "unit", "mj", "measure"]
  qty: ["množství", "mnozstvi", "quantity", "qty"]
  unit_price: ["cena za mj", "unit price", "rate", "cena/mj"]
  total_price: ["cena celkem", "total price", "celkem", "line total"]
  discipline_hint: ["disciplína", "disciplina", "discipline"]
  vat_rate: ["dph", "vat"]
  currency: ["měna", "mena", "currency"]

unit_map:
  m:
    aliases: ["m", "metr", "meter"]
    target_unit: m
    factor: 1.0
  mm:
    aliases: ["mm", "milimetr", "millimeter"]
    target_unit: m
    factor: 0.001
  m2:
    aliases: ["m2", "m^2", "sqm", "m²"]
    target_unit: m2
    factor: 1.0
  m3:
    aliases: ["m3", "m^3", "cbm", "m³"]
    target_unit: m3
    factor: 1.0
  ks:
    aliases: ["ks", "kus", "pcs", "piece"]
    target_unit: pcs
    factor: 1.0
  pcs:
    aliases: ["pc", "pcs", "piece"]
    target_unit: pcs
    factor: 1.0
  h:
    aliases: ["h", "hod", "hodina", "hour"]
    target_unit: h
    factor: 1.0
  kw:
    aliases: ["kw", "kilowatt"]
    target_unit: kw
    factor: 1.0
  w:
    aliases: ["w", "watt"]
    target_unit: kw
    factor: 0.001

currency:
  base: CZK
  default_vat: 0.21
  rates:
    CZK: 1.0
    EUR: 24.5
    USD: 22.0

# Discipline synonyms used for tagging and search
# Regular expressions are matched case-insensitively.
disciplines:
  synonyms:
    VZT:
      - "\\b(vzt|vzduchotechnika|ahu|air handling unit|hvac)\\b"
      - "vzduchotechn"
    ELE:
      - "\\b(ele|elektro|electrical|svítidlo|rozvaděč|kabel)\\b"
    ZTI:
      - "\\b(zti|voda|sanita|plumbing|kanalizace)\\b"
    CHL:
      - "\\b(chl|chlazení|chiller|cooling)\\b"
    VYT:
      - "\\b(vyt|vytápění|heating|kotel)\\b"
    SHZ:
      - "\\b(shz|sprinkler|haseni|fire suppression)\\b"
    STAT:
      - "\\b(stat|statika|ocel|steel|beton|konstrukce)\\b"
    ARK:
      - "\\b(ark|architekt|architectural|finishe?s)\\b"
    PSD:
      - "\\b(psd|projekt|project documentation|dokumentace)\\b"
    OSTATNI:
      - "\\b(ostatní|other|misc)\\b"

# Hierarchical work breakdown structure
wbs:
  - code: "01"
    name: "ZTI"
    discipline: "ZTI"
    description: "Zdravotně technické instalace"
    keywords: ["zti", "voda", "kanalizace", "sanita"]
    children:
      - code: "01.01"
        name: "Rozvody vody"
        discipline: "ZTI"
        description: "Potrubí studené a teplé vody"
        keywords: ["water distribution", "potrubí"]
        unit: "m"
      - code: "01.02"
        name: "Zařizovací předměty"
        discipline: "ZTI"
        description: "Sanitární zařizovací předměty"
        keywords: ["sanitary fixtures"]
        unit: "pcs"
  - code: "02"
    name: "ELE"
    discipline: "ELE"
    description: "Silnoproudé elektro"
    keywords: ["elektro", "cable", "rozvod"]
    children:
      - code: "02.01"
        name: "Rozvaděče"
        discipline: "ELE"
        description: "Elektrické rozvaděče a panely"
        keywords: ["switchboard", "distribution panel"]
        unit: "pcs"
      - code: "02.02"
        name: "Kabeláž"
        discipline: "ELE"
        description: "Napájecí a datová kabeláž"
        keywords: ["cable", "kabel"]
        unit: "m"
  - code: "03"
    name: "VZT"
    discipline: "VZT"
    description: "Vzduchotechnika"
    keywords: ["vzt", "hvac", "air handling"]
    children:
      - code: "03.01"
        name: "Vzduchotechnické jednotky"
        discipline: "VZT"
        description: "Dodávka AHU jednotek"
        keywords: ["ahu", "air handling unit", "vzt jednotka"]
        unit: "pcs"
      - code: "03.02"
        name: "Vzduchotechnické potrubí"
        discipline: "VZT"
        description: "Potrubní sítě a příslušenství"
        keywords: ["duct", "potrubí", "hvac duct"]
        unit: "m2"
